name: Warm Render
on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 min
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        url:
          - https://interview-suite.onrender.com/healthz
          - https://interview-suite-pollar.onrender.com/health
    steps:
      - name: Curl ${{ matrix.url }}
        run: |
          set -e
          http_code=$(curl -fsS -o /dev/null -w "%{http_code}" --max-time 15 "${{ matrix.url }}")
          echo "HTTP $http_code for ${{ matrix.url }}"
          if [ "$http_code" -ge 400 ] || [ "$http_code" -lt 200 ]; then
            exit 1
          fi
